matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      language: generic
      env: TYPE="osx" PYTHON="python2" PYARGS="-R" APT_PACKAGES=""
    - os: osx
      osx_image: xcode6.4
      language: generic
      env: TYPE="osx" PYTHON="python3" PYARGS="-R -bb" APT_PACKAGES=""

install:
 - if [ "$TYPE" == "osx" ] && [ "$PYTHON" == "python2" ]; then travis_retry wget https://bitbucket.org/lazka/quodlibet/downloads/QuodLibet-latest.dmg; fi
 - if [ "$TYPE" == "osx" ] && [ "$PYTHON" == "python2" ]; then hdiutil attach -readonly -mountpoint _mount QuodLibet-latest.dmg; fi
 - if [ "$TYPE" == "osx" ] && [ "$PYTHON" == "python3" ]; then travis_retry wget https://bitbucket.org/lazka/quodlibet/downloads/QuodLibet-latest-Py3.dmg; fi
 - if [ "$TYPE" == "osx" ] && [ "$PYTHON" == "python3" ]; then hdiutil attach -readonly -mountpoint _mount QuodLibet-latest-Py3.dmg; fi

script:
 - cd quodlibet
 - if [ "$TYPE" == "osx" ]; then ../_mount/QuodLibet.app/Contents/MacOS/run $PYARGS setup.py test; fi
