matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      language: generic
    - os: osx
      osx_image: xcode8
      language: generic
    - os: osx
      osx_image: xcode9.4
      language: generic

install:
 - travis_retry wget -O ql.dmg https://github.com/quodlibet/quodlibet/releases/download/ci/QuodLibet-latest-v4.dmg
 - hdiutil attach -readonly -mountpoint _mount ql.dmg

script:
 - cd quodlibet
 - ../_mount/QuodLibet.app/Contents/MacOS/run -R -bb -m coverage run --branch setup.py test
 - ../_mount/QuodLibet.app/Contents/MacOS/run -R -bb -m coverage xml
 - bash <(curl -s https://codecov.io/bash)
