matrix:
  allow_failures:
    - python: "3.4_with_system_site_packages"
  include:
    - os: linux
      sudo: required
      dist: trusty
      language: python
      python: "2.7_with_system_site_packages"
      env: TYPE="linux" PYTHON="python2" APT_PACKAGES="quodlibet exfalso xvfb"
    - os: linux
      sudo: required
      dist: trusty
      language: python
      python: "3.4_with_system_site_packages"
      env: TYPE="linux" PYTHON="python3" APT_PACKAGES="quodlibet exfalso xvfb python3-mutagen python3-gi python3-gi-cairo"
    - os: osx
      language: generic
      env: TYPE="osx" APT_PACKAGES=""
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env: TYPE="windows" APT_PACKAGES="wine xvfb"

install:
 - if [ "$APT_PACKAGES" != "" ]; then sudo dpkg --add-architecture i386; fi
 - if [ "$APT_PACKAGES" != "" ]; then sudo add-apt-repository -y ppa:lazka/dumpingplace; fi
 - if [ "$APT_PACKAGES" != "" ]; then sudo apt-get update -q || true; fi
 - if [ "$APT_PACKAGES" != "" ]; then sudo apt-get install -y $(echo $APT_PACKAGES); fi
 - if [ "$TYPE" == "linux" ]; then pip install --upgrade pep8 pyflakes; fi
 - if [ "$TYPE" == "osx" ]; then wget http://bitbucket.org/lazka/quodlibet/downloads/QuodLibet-3.6.1.zip; fi
 - if [ "$TYPE" == "osx" ]; then unzip -qq QuodLibet-3.6.1.zip; fi
 - if [ "$TYPE" == "windows" ]; then wget https://bitbucket.org/lazka/quodlibet/downloads/quodlibet-3.6-win-sdk.tar.xz; fi
 - if [ "$TYPE" == "windows" ]; then tar -xJf quodlibet-3.6-win-sdk.tar.xz; fi

script:
 - cd quodlibet
 - if [ "$TYPE" == "linux" ]; then xvfb-run -a $PYTHON ./setup.py test; fi
 - if [ "$TYPE" == "linux" ]; then xvfb-run -a $PYTHON ./setup.py quality; fi
 - if [ "$TYPE" == "osx" ]; then ../QuodLibet.app/Contents/MacOS/run setup.py test; fi
 - if [ "$TYPE" == "windows" ]; then xvfb-run -a ../_sdk/test_ci.sh ./setup.py test; fi
