defaults: &defaults
  working_directory: ~/workdir
  machine: true
  steps:
    - checkout
    - run: pwd; ls -l
    - run: docker info
    - run:
        # One cache per job and release branch
        command: |
          echo "$DOCKERIMAGE" > _cache_key_file
          grep "BRANCH_NAME =" quodlibet/quodlibet/const.py >> _cache_key_file
          cat _cache_key_file
    - restore_cache:
        key: cache-{{ checksum "_cache_key_file" }}
    - run: ls -l _ci_cache || true
    - run:
        command: |
          if [ ! -f "_ci_cache/$DOCKERIMAGE" ]; then
          .circleci/retry docker build -t "$DOCKERIMAGE" -f ".docker/Dockerfile.$DOCKERIMAGE" .;
          mkdir -p _ci_cache;
          docker image save "$DOCKERIMAGE" -o "_ci_cache/$DOCKERIMAGE";
          fi;
    - save_cache:
        key: cache-{{ checksum "_cache_key_file" }}
        paths:
          - _ci_cache
    - run: docker image load -i "_ci_cache/$DOCKERIMAGE"
    - run: docker run --volume "$(pwd):/home/user/app" --workdir "/home/user/app/quodlibet" --tty --detach "$DOCKERIMAGE" bash > container_id
    - run: docker exec "$(cat container_id)" $PYTHON $PYARGS ./setup.py test
    - run: docker stop "$(cat container_id)"

version: 2
jobs:
  job.debian8.py2:
    environment:
      - PYARGS: "-R"
      - PYTHON: "python2"
      - DOCKERIMAGE: "debian8.py2"
    <<: *defaults
  job.debian8.py3:
    environment:
      - PYARGS: "-R -bb"
      - PYTHON: "python3"
      - DOCKERIMAGE: "debian8.py3"
    <<: *defaults
  job.ubuntu16.04.py2:
    environment:
      - PYARGS: "-R"
      - PYTHON: "python2"
      - DOCKERIMAGE: "ubuntu16.04.py2"
    <<: *defaults
  job.ubuntu16.04.py3:
    environment:
      - PYARGS: "-R -bb"
      - PYTHON: "python3"
      - DOCKERIMAGE: "ubuntu16.04.py3"
    <<: *defaults
  job.ubuntu17.10.py3:
    environment:
      - PYARGS: "-R -bb"
      - PYTHON: "python3"
      - DOCKERIMAGE: "ubuntu17.10.py3"
    <<: *defaults
  job.win32.py2:
    environment:
      - PYARGS: "-R"
      - PYTHON: "python2"
      - DOCKERIMAGE: "win32.py2"
    <<: *defaults
  job.win32.py3:
    environment:
      - PYARGS: "-R"
      - PYTHON: "python3"
      - DOCKERIMAGE: "win32.py3"
    <<: *defaults

workflows:
  version: 2
  build_and_test:
    jobs:
      - job.win32.py2
      - job.win32.py3
      - job.debian8.py2
      - job.debian8.py3
      - job.ubuntu16.04.py2
      - job.ubuntu16.04.py3
      - job.ubuntu17.10.py3
