defaults: &defaults
  working_directory: ~/workdir
  machine: true
  steps:
    - checkout
    - run: mkdir test-results
    - run: docker info
    - run:
        command: |
          cp ".docker/Dockerfile.$DOCKERIMAGE" _cache_key_file;
          echo "CACHE-VERSION-1" >> _cache_key_file;
    - restore_cache:
        key: cache-{{ checksum "_cache_key_file" }}
    - run: ls -l _ci_cache || true
    - run:
        command: |
          if [ ! -f "_ci_cache/$DOCKERIMAGE" ]; then
          .circleci/retry docker build --build-arg HOST_USER_ID="$UID" -t "$DOCKERIMAGE" -f ".docker/Dockerfile.$DOCKERIMAGE" .;
          mkdir -p _ci_cache;
          docker image save "$DOCKERIMAGE" -o "_ci_cache/$DOCKERIMAGE";
          fi;
    - save_cache:
        key: cache-{{ checksum "_cache_key_file" }}
        paths:
          - _ci_cache
    - run: docker image load -i "_ci_cache/$DOCKERIMAGE"
    - run: docker run $(bash <(curl -s https://codecov.io/env)) --volume "$(pwd):/home/user/app" --workdir "/home/user/app/quodlibet" --tty --detach "$DOCKERIMAGE" bash > container_id
    - run: docker exec "$(cat container_id)" python3 -R -bb -m coverage run --branch ./setup.py test
    - store_test_results:
        path: test-results
    - run:
        command: |
          docker exec "$(cat container_id)" python3 -m coverage xml
          docker exec "$(cat container_id)" curl https://codecov.io/bash -o _codecov
          docker exec "$(cat container_id)" bash _codecov
        when: always
    - run:
        command: docker stop "$(cat container_id)"
        when: always

version: 2
jobs:
  job.ubuntu16.04:
    environment:
      - DOCKERIMAGE: "ubuntu16.04"
    <<: *defaults
  job.ubuntu18.04:
    environment:
      - DOCKERIMAGE: "ubuntu18.04"
    <<: *defaults
  job.win32:
    environment:
      - DOCKERIMAGE: "win32"
    <<: *defaults
  job.fedora28:
    environment:
      - DOCKERIMAGE: "fedora28"
    <<: *defaults

workflows:
  version: 2
  build_and_test:
    jobs:
      - job.win32
      - job.ubuntu16.04
      - job.ubuntu18.04
      - job.fedora28
